### ISSUE TITLE
Reduce number of open-ended questions

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/rails-api-diagnostic#2]
For example:

```
What is the purpose of a model in the MVC pattern?
```

Answers are easier to evaluate when inverted, Jeopardy style:

```
Which layer in the MVC pattern is used by the controller to fetch data?
```

**Comment by RealWeeks** [comment]
applied for some questions where it makes sense

**Comment by jrhorn424** [comment]
@J-Weeks This is great. In general, it's polite to ask others who open issues whether it's ok to close them, even when you've added a fix.

Also, it's polite to refer to the commit if you haven't mentioned the issue number in a commit message. https://help.github.com/articles/closing-issues-via-commit-messages/
