### ISSUE TITLE
Add questions that ask developers to demonstrate familiarity with command line tools

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/rails-api-diagnostic#3]

**Comment by RealWeeks** [comment]
multiple questions added

**Comment by jrhorn424** [comment]
@J-Weeks This is great. In general, it's polite to ask others who open issues whether it's ok to close them, even when you've added a fix.

Also, it's polite to refer to the commit if you haven't mentioned the issue number in a commit message. https://help.github.com/articles/closing-issues-via-commit-messages/
