### ISSUE TITLE
this repo has a duplicate

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/rails-api-diagnostic#82]
https://github.com/ga-wdi-boston/rails-api-single-diagnostic

**Comment by payne-chris-r** [comment]
It does not anymore. `rails-api-single-diagnostic` is now different: https://github.com/ga-wdi-boston/rails-api-single-diagnostic/commit/c811bf2c552e7d35bdd8754bfd1b6c26ccc96335
